"""The committed catalog must be exactly what the current generator produces.

`tests/tools/test_codegen_idempotent.py` proves two runs agree with each
other; that passes even when the committed tree is stale, hand-edited or was
generated by an older `CODEGEN_VERSION`. This module closes that gap: it
regenerates from the committed `schemas.json` and compares byte for byte with
`src/opensees_studio/core/catalog/`.

A failure here has one of two causes, and the message says which files:

- the generator changed and the tree was not regenerated;
- somebody edited a file under `generated/`, which the codegen README forbids.

Either way the fix is the same command the message prints.
"""

from __future__ import annotations

from pathlib import Path

from tools.gidopensees_import.codegen import (
    _source_stamp,
    run_codegen,
)

ROOT = Path(__file__).resolve().parents[2]
SCHEMAS = ROOT / "tools" / "gidopensees_import" / "schemas.json"
COMMITTED = ROOT / "src" / "opensees_studio" / "core" / "catalog"


def _snapshot(root: Path, *, prefix: str = "") -> dict[str, bytes]:
    """Every ``*.py`` under ``root``, keyed by its path relative to ``root``.

    ``prefix`` is stripped from the keys so a tree generated into
    ``<tmp>/catalog/generated`` and the committed ``core/catalog`` can be
    compared with the same names.
    """
    out: dict[str, bytes] = {}
    for path in sorted(root.rglob("*.py")):
        rel = path.relative_to(root).as_posix()
        if prefix and rel.startswith(prefix):
            rel = rel[len(prefix) :]
        out[rel] = path.read_bytes()
    return out


def _report(name: str, committed: dict[str, bytes], fresh: dict[str, bytes]) -> str:
    """A message a reader can act on, not a dict comparison dump."""
    lines = [f"{name} does not match a fresh codegen run:"]
    for rel in sorted(set(fresh) - set(committed)):
        lines.append(f"  missing from the repo: {rel}")
    for rel in sorted(set(committed) - set(fresh)):
        lines.append(f"  not produced by the generator: {rel}")
    for rel in sorted(set(committed) & set(fresh)):
        if committed[rel] != fresh[rel]:
            lines.append(f"  differs: {rel}")
    lines.append(
        "\nRegenerate with:\n"
        "  python -m tools.gidopensees_import.codegen "
        f"--schemas {SCHEMAS.relative_to(ROOT)} --out "
        f"{COMMITTED.relative_to(ROOT)}/generated"
    )
    return "\n".join(lines)


def test_the_committed_catalog_is_current(tmp_path: Path) -> None:
    """Also fails if a generated file was edited by hand."""
    run_codegen(SCHEMAS, tmp_path / "catalog" / "generated")
    fresh = _snapshot(tmp_path, prefix="catalog/")
    committed = _snapshot(COMMITTED)

    assert fresh == committed, _report("src/opensees_studio/core/catalog", committed, fresh)


def test_the_stamp_of_the_committed_tree_is_the_current_one() -> None:
    """A cheap canary: the stamp moves when schemas.json or the generator does."""
    stamp = _source_stamp(SCHEMAS)
    generated = sorted((COMMITTED / "generated").glob("*.py"))
    assert generated, "the generated catalog is not in the tree"
    for path in generated:
        head = path.read_text(encoding="utf-8").splitlines()[:4]
        assert any(stamp in line for line in head), (
            f"{path.name} was generated by an older codegen; {stamp} is current"
        )
