"""Pure-Python domain layer.

This package never imports Qt or openseespy. Anything in here is safe
to use from a script, a Jupyter notebook, or a future CLI.
"""

from opensees_studio.core.analysis import (
    AnalysisCase,
    ModalCase,
    PushoverCase,
    ResponseSpectrumCase,
    StaticCase,
    TransientCase,
)
from opensees_studio.core.constraints import EqualDOFConstraint
from opensees_studio.core.defaults import (
    DEFAULT_PATTERN_NAME,
    DEFAULT_TRUSS_AREA,
    ensure_default_section,
    ensure_default_timeseries_and_pattern,
    ensure_default_truss_material,
    find_default_section,
    find_default_truss_material,
    find_plain_pattern,
    make_default_pattern,
    make_default_section,
    make_default_time_series,
    make_default_truss_material,
)
from opensees_studio.core.geometry import (
    BeamWithHingesElement,
    CoordinateGridSystem,
    CoordinateSystem,
    CorotTrussElement,
    DispBeamColumn,
    ElasticBeamColumn,
    Element,
    ForceBeamColumn,
    GridLine,
    GridSystem,
    Node,
    QuadElement,
    TrussElement,
    ZeroLengthElement,
    ZeroLengthSectionElement,
    default_global_system,
    make_grid_lines,
)
from opensees_studio.core.ground_motion import (
    GroundMotionFormat,
    GroundMotionRecord,
    content_hash_of_bytes,
    content_hash_of_file,
    detect_format,
    import_record,
    read_peer_at2,
    read_plain_values,
    read_record,
    read_single_column,
    read_two_column,
    sanitize_record_filename,
)
from opensees_studio.core.ground_motion_metadata import (
    GroundMotionMetadata,
    arias_intensity,
    compute_metadata,
    pga,
    pgd,
    pgv,
    significant_duration_5_95,
    total_duration,
)
from opensees_studio.core.loads import (
    ConstantTimeSeries,
    ImposedSupportMotionPattern,
    LinearTimeSeries,
    LoadPattern,
    NodalLoad,
    PathTimeSeries,
    PlainLoadPattern,
    ResponseSpectrum,
    TimeSeries,
    UniformElementLoad,
    UniformExcitationPattern,
)
from opensees_studio.core.materials import (
    Concrete01,
    Concrete02,
    Concrete04,
    ElasticIsotropic,
    ElasticPP,
    ElasticUniaxial,
    HystereticMaterial,
    HystereticSM,
    Material,
    Steel01,
    Steel02,
)
from opensees_studio.core.project import Project, ProjectMeta
from opensees_studio.core.response_spectrum import (
    DEFAULT_DAMPING,
    ElasticSpectrum,
    default_periods,
    response_spectrum,
    sdof_response,
)
from opensees_studio.core.sections import (
    AggregatorDOF,
    AngleShape,
    CircularPatch,
    ElasticSection,
    FiberSection,
    Fibre,
    PipeShape,
    RectangularPatch,
    RectShape,
    Section,
    SectionAggregator,
    SectionShape,
    StraightLayer,
)
from opensees_studio.core.units import UnitLabels, UnitSystem, labels_for

__all__ = [  # noqa: RUF022 - grouped by domain under section comments, not alphabetical
    # Project + meta
    "Project",
    "ProjectMeta",
    "UnitSystem",
    "UnitLabels",
    "labels_for",
    # Geometry
    "Node",
    "EqualDOFConstraint",
    # Auto-infrastructure defaults (shared with the web backend)
    "DEFAULT_TRUSS_AREA",
    "DEFAULT_PATTERN_NAME",
    "make_default_section",
    "make_default_truss_material",
    "make_default_time_series",
    "make_default_pattern",
    "find_default_section",
    "find_default_truss_material",
    "find_plain_pattern",
    "ensure_default_section",
    "ensure_default_truss_material",
    "ensure_default_timeseries_and_pattern",
    "Element",
    "TrussElement",
    "CorotTrussElement",
    "ElasticBeamColumn",
    "ForceBeamColumn",
    "DispBeamColumn",
    "ZeroLengthElement",
    "ZeroLengthSectionElement",
    "BeamWithHingesElement",
    "QuadElement",
    "GridSystem",
    "GridLine",
    "CoordinateSystem",
    "CoordinateGridSystem",
    "default_global_system",
    "make_grid_lines",
    # Materials
    "Material",
    "ElasticIsotropic",
    "ElasticUniaxial",
    "Steel01",
    "Steel02",
    "Concrete01",
    "Concrete02",
    "Concrete04",
    "ElasticPP",
    "HystereticMaterial",
    "HystereticSM",
    # Sections
    "Section",
    "ElasticSection",
    "FiberSection",
    "Fibre",
    "RectangularPatch",
    "CircularPatch",
    "StraightLayer",
    "SectionAggregator",
    "AggregatorDOF",
    # Optional cosmetic section-shape hints (extruded-view drawing only)
    "SectionShape",
    "PipeShape",
    "AngleShape",
    "RectShape",
    # Loads
    "TimeSeries",
    "LinearTimeSeries",
    "ConstantTimeSeries",
    "PathTimeSeries",
    "LoadPattern",
    "PlainLoadPattern",
    "UniformExcitationPattern",
    "ImposedSupportMotionPattern",
    "NodalLoad",
    "UniformElementLoad",
    "ResponseSpectrum",
    # Ground motions
    "GroundMotionRecord",
    "GroundMotionFormat",
    "content_hash_of_bytes",
    "content_hash_of_file",
    "detect_format",
    "read_peer_at2",
    "read_plain_values",
    "read_two_column",
    "read_single_column",
    "read_record",
    "import_record",
    "sanitize_record_filename",
    "GroundMotionMetadata",
    "compute_metadata",
    "pga",
    "pgv",
    "pgd",
    "arias_intensity",
    "significant_duration_5_95",
    "total_duration",
    "DEFAULT_DAMPING",
    "ElasticSpectrum",
    "default_periods",
    "response_spectrum",
    "sdof_response",
    # Analysis
    "AnalysisCase",
    "StaticCase",
    "ModalCase",
    "TransientCase",
    "PushoverCase",
    "ResponseSpectrumCase",
]
