"""Pure-Python domain layer.

This package never imports Qt or openseespy. Anything in here is safe
to use from a script, a Jupyter notebook, or a future CLI.
"""

from opensees_studio.core.analysis import (
    AnalysisCase,
    ModalCase,
    PushoverCase,
    ResponseSpectrumCase,
    StaticCase,
    TransientCase,
)
from opensees_studio.core.constraints import EqualDOFConstraint
from opensees_studio.core.defaults import (
    DEFAULT_PATTERN_NAME,
    DEFAULT_TRUSS_AREA,
    ensure_default_section,
    ensure_default_timeseries_and_pattern,
    ensure_default_truss_material,
    find_default_section,
    find_default_truss_material,
    find_plain_pattern,
    make_default_pattern,
    make_default_section,
    make_default_time_series,
    make_default_truss_material,
)
from opensees_studio.core.geometry import (
    BeamWithHingesElement,
    CoordinateGridSystem,
    CoordinateSystem,
    CorotTrussElement,
    DispBeamColumn,
    ElasticBeamColumn,
    Element,
    ForceBeamColumn,
    GridLine,
    GridSystem,
    Node,
    QuadElement,
    TrussElement,
    ZeroLengthElement,
    ZeroLengthSectionElement,
    default_global_system,
    make_grid_lines,
)
from opensees_studio.core.loads import (
    ConstantTimeSeries,
    LinearTimeSeries,
    LoadPattern,
    NodalLoad,
    PathTimeSeries,
    PlainLoadPattern,
    ResponseSpectrum,
    TimeSeries,
    UniformElementLoad,
    UniformExcitationPattern,
)
from opensees_studio.core.materials import (
    Concrete01,
    Concrete02,
    Concrete04,
    ElasticIsotropic,
    ElasticPP,
    ElasticUniaxial,
    HystereticMaterial,
    HystereticSM,
    Material,
    Steel01,
    Steel02,
)
from opensees_studio.core.project import Project, ProjectMeta
from opensees_studio.core.sections import (
    AggregatorDOF,
    CircularPatch,
    ElasticSection,
    FiberSection,
    Fibre,
    RectangularPatch,
    Section,
    SectionAggregator,
    StraightLayer,
)
from opensees_studio.core.units import UnitLabels, UnitSystem, labels_for

__all__ = [
    # Project + meta
    "Project",
    "ProjectMeta",
    "UnitSystem",
    "UnitLabels",
    "labels_for",
    # Geometry
    "Node",
    "EqualDOFConstraint",
    # Auto-infrastructure defaults (shared with the web backend)
    "DEFAULT_TRUSS_AREA",
    "DEFAULT_PATTERN_NAME",
    "make_default_section",
    "make_default_truss_material",
    "make_default_time_series",
    "make_default_pattern",
    "find_default_section",
    "find_default_truss_material",
    "find_plain_pattern",
    "ensure_default_section",
    "ensure_default_truss_material",
    "ensure_default_timeseries_and_pattern",
    "Element",
    "TrussElement",
    "CorotTrussElement",
    "ElasticBeamColumn",
    "ForceBeamColumn",
    "DispBeamColumn",
    "ZeroLengthElement",
    "ZeroLengthSectionElement",
    "BeamWithHingesElement",
    "QuadElement",
    "GridSystem",
    "GridLine",
    "CoordinateSystem",
    "CoordinateGridSystem",
    "default_global_system",
    "make_grid_lines",
    # Materials
    "Material",
    "ElasticIsotropic",
    "ElasticUniaxial",
    "Steel01",
    "Steel02",
    "Concrete01",
    "Concrete02",
    "Concrete04",
    "ElasticPP",
    "HystereticMaterial",
    "HystereticSM",
    # Sections
    "Section",
    "ElasticSection",
    "FiberSection",
    "Fibre",
    "RectangularPatch",
    "CircularPatch",
    "StraightLayer",
    "SectionAggregator",
    "AggregatorDOF",
    # Loads
    "TimeSeries",
    "LinearTimeSeries",
    "ConstantTimeSeries",
    "PathTimeSeries",
    "LoadPattern",
    "PlainLoadPattern",
    "UniformExcitationPattern",
    "NodalLoad",
    "UniformElementLoad",
    "ResponseSpectrum",
    # Analysis
    "AnalysisCase",
    "StaticCase",
    "ModalCase",
    "TransientCase",
    "PushoverCase",
    "ResponseSpectrumCase",
]
