# ruff: noqa
# AUTOGENERATED - do not edit.  Generated: 2026-05-22T07:11:32Z
# Flat CATALOG mapping gidopensees material name -> Pydantic Spec class.

from __future__ import annotations

from pydantic import BaseModel

from opensees_studio.core.catalog.generated.elastic import ElasticSpec
from opensees_studio.core.catalog.generated.elastic_perfectly_plastic import ElasticPerfectlyPlasticSpec
from opensees_studio.core.catalog.generated.elastic_perfectly_plastic_with_gap import ElasticPerfectlyPlasticWithGapSpec
from opensees_studio.core.catalog.generated.viscous import ViscousSpec
from opensees_studio.core.catalog.generated.viscous_damper import ViscousDamperSpec
from opensees_studio.core.catalog.generated.hyperbolic_gap import HyperbolicGapSpec
from opensees_studio.core.catalog.generated.pysimple1 import Pysimple1Spec
from opensees_studio.core.catalog.generated.tzsimple1 import Tzsimple1Spec
from opensees_studio.core.catalog.generated.qzsimple1 import Qzsimple1Spec
from opensees_studio.core.catalog.generated.bondsp01 import Bondsp01Spec
from opensees_studio.core.catalog.generated.steel01 import Steel01Spec
from opensees_studio.core.catalog.generated.steel02 import Steel02Spec
from opensees_studio.core.catalog.generated.reinforcing_steel import ReinforcingSteelSpec
from opensees_studio.core.catalog.generated.hysteretic import HystereticSpec
from opensees_studio.core.catalog.generated.ramberg_osgood_steel import RambergOsgoodSteelSpec
from opensees_studio.core.catalog.generated.concrete01_zero_tensile_strength import Concrete01ZeroTensileStrengthSpec
from opensees_studio.core.catalog.generated.concrete02_linear_tension_softening import Concrete02LinearTensionSofteningSpec
from opensees_studio.core.catalog.generated.concrete04_popovics_concrete import Concrete04PopovicsConcreteSpec
from opensees_studio.core.catalog.generated.concrete06 import Concrete06Spec
from opensees_studio.core.catalog.generated.concretecm import ConcretecmSpec
from opensees_studio.core.catalog.generated.series import SeriesSpec
from opensees_studio.core.catalog.generated.parallel import ParallelSpec
from opensees_studio.core.catalog.generated.section_aggregator import SectionAggregatorSpec
from opensees_studio.core.catalog.generated.initial_strain import InitialStrainSpec
from opensees_studio.core.catalog.generated.initial_stress import InitialStressSpec
from opensees_studio.core.catalog.generated.minmax import MinmaxSpec
from opensees_studio.core.catalog.generated.user_material import UserMaterialSpec
from opensees_studio.core.catalog.generated.elastic_isotropic import ElasticIsotropicSpec
from opensees_studio.core.catalog.generated.elastic_orthotropic import ElasticOrthotropicSpec
from opensees_studio.core.catalog.generated.j2plasticity import J2plasticitySpec
from opensees_studio.core.catalog.generated.damage2p import Damage2pSpec
from opensees_studio.core.catalog.generated.pressureindependmultiyield import PressureindependmultiyieldSpec
from opensees_studio.core.catalog.generated.pressuredependmultiyield import PressuredependmultiyieldSpec
from opensees_studio.core.catalog.generated.pressuredependmultiyield02 import Pressuredependmultiyield02Spec
from opensees_studio.core.catalog.generated.contact import ContactSpec
from opensees_studio.core.catalog.generated.elastic_section import ElasticSectionSpec
from opensees_studio.core.catalog.generated.fiber import FiberSpec
from opensees_studio.core.catalog.generated.fiber_custom import FiberCustomSpec
from opensees_studio.core.catalog.generated.fiberint import FiberintSpec
from opensees_studio.core.catalog.generated.plate_fiber import PlateFiberSpec
from opensees_studio.core.catalog.generated.elastic_membrane_plate import ElasticMembranePlateSpec
from opensees_studio.core.catalog.generated.layeredshell import LayeredshellSpec
from opensees_studio.core.catalog.generated.ground_motion_record import GroundMotionRecordSpec
from opensees_studio.core.catalog.generated.elastic_beam_column import ElasticBeamColumnSpec
from opensees_studio.core.catalog.generated.elastic_timoshenko_beam_column import ElasticTimoshenkoBeamColumnSpec
from opensees_studio.core.catalog.generated.force_based_beam_column import ForceBasedBeamColumnSpec
from opensees_studio.core.catalog.generated.displacement_based_beam_column import DisplacementBasedBeamColumnSpec
from opensees_studio.core.catalog.generated.flexure_shear_interaction_displacement_based_beam_column import FlexureShearInteractionDisplacementBasedBeamColumnSpec
from opensees_studio.core.catalog.generated.truss import TrussSpec
from opensees_studio.core.catalog.generated.corotational_truss import CorotationalTrussSpec
from opensees_studio.core.catalog.generated.quad import QuadSpec
from opensees_studio.core.catalog.generated.shell import ShellSpec
from opensees_studio.core.catalog.generated.shelldkgq import ShelldkgqSpec
from opensees_studio.core.catalog.generated.tri31 import Tri31Spec
from opensees_studio.core.catalog.generated.quadup import QuadupSpec
from opensees_studio.core.catalog.generated.standard_brick_element import StandardBrickElementSpec
from opensees_studio.core.catalog.generated.auto_zero_length import AutoZeroLengthSpec
from opensees_studio.core.catalog.generated.auto_equal_constraint import AutoEqualConstraintSpec


CATALOG: dict[str, type[BaseModel]] = {
    'Elastic': ElasticSpec,
    'Elastic_Perfectly_Plastic': ElasticPerfectlyPlasticSpec,
    'Elastic_Perfectly_Plastic_with_Gap': ElasticPerfectlyPlasticWithGapSpec,
    'Viscous': ViscousSpec,
    'Viscous_Damper': ViscousDamperSpec,
    'Hyperbolic_Gap': HyperbolicGapSpec,
    'PySimple1': Pysimple1Spec,
    'TzSimple1': Tzsimple1Spec,
    'QzSimple1': Qzsimple1Spec,
    'BondSP01': Bondsp01Spec,
    'Steel01': Steel01Spec,
    'Steel02': Steel02Spec,
    'Reinforcing_steel': ReinforcingSteelSpec,
    'Hysteretic': HystereticSpec,
    'Ramberg-Osgood steel': RambergOsgoodSteelSpec,
    'Concrete01_(Zero_tensile_strength)': Concrete01ZeroTensileStrengthSpec,
    'Concrete02_(Linear_tension_softening)': Concrete02LinearTensionSofteningSpec,
    'Concrete04_(Popovics_concrete)': Concrete04PopovicsConcreteSpec,
    'Concrete06': Concrete06Spec,
    'ConcreteCM': ConcretecmSpec,
    'Series': SeriesSpec,
    'Parallel': ParallelSpec,
    'Section_Aggregator': SectionAggregatorSpec,
    'Initial_Strain': InitialStrainSpec,
    'Initial_Stress': InitialStressSpec,
    'MinMax': MinmaxSpec,
    'User_Material': UserMaterialSpec,
    'Elastic_Isotropic': ElasticIsotropicSpec,
    'Elastic_Orthotropic': ElasticOrthotropicSpec,
    'J2Plasticity': J2plasticitySpec,
    'Damage2p': Damage2pSpec,
    'PressureIndependMultiYield': PressureindependmultiyieldSpec,
    'PressureDependMultiYield': PressuredependmultiyieldSpec,
    'PressureDependMultiYield02': Pressuredependmultiyield02Spec,
    'Contact': ContactSpec,
    'Elastic_Section': ElasticSectionSpec,
    'Fiber': FiberSpec,
    'Fiber_Custom': FiberCustomSpec,
    'FiberInt': FiberintSpec,
    'Plate_Fiber': PlateFiberSpec,
    'Elastic_Membrane_Plate': ElasticMembranePlateSpec,
    'LayeredShell': LayeredshellSpec,
    'Ground_Motion_Record': GroundMotionRecordSpec,
    'Elastic_Beam-Column': ElasticBeamColumnSpec,
    'Elastic_Timoshenko_Beam-Column': ElasticTimoshenkoBeamColumnSpec,
    'Force-Based_Beam-Column': ForceBasedBeamColumnSpec,
    'Displacement-Based_Beam-Column': DisplacementBasedBeamColumnSpec,
    'Flexure-Shear_Interaction_Displacement-Based_Beam-Column': FlexureShearInteractionDisplacementBasedBeamColumnSpec,
    'Truss': TrussSpec,
    'Corotational_Truss': CorotationalTrussSpec,
    'Quad': QuadSpec,
    'Shell': ShellSpec,
    'ShellDKGQ': ShelldkgqSpec,
    'Tri31': Tri31Spec,
    'QuadUP': QuadupSpec,
    'Standard_Brick_Element': StandardBrickElementSpec,
    'Auto_Zero_Length': AutoZeroLengthSpec,
    'Auto_equal_constraint': AutoEqualConstraintSpec,
}

__all__ = ["CATALOG", 'ElasticSpec', 'ElasticPerfectlyPlasticSpec', 'ElasticPerfectlyPlasticWithGapSpec', 'ViscousSpec', 'ViscousDamperSpec', 'HyperbolicGapSpec', 'Pysimple1Spec', 'Tzsimple1Spec', 'Qzsimple1Spec', 'Bondsp01Spec', 'Steel01Spec', 'Steel02Spec', 'ReinforcingSteelSpec', 'HystereticSpec', 'RambergOsgoodSteelSpec', 'Concrete01ZeroTensileStrengthSpec', 'Concrete02LinearTensionSofteningSpec', 'Concrete04PopovicsConcreteSpec', 'Concrete06Spec', 'ConcretecmSpec', 'SeriesSpec', 'ParallelSpec', 'SectionAggregatorSpec', 'InitialStrainSpec', 'InitialStressSpec', 'MinmaxSpec', 'UserMaterialSpec', 'ElasticIsotropicSpec', 'ElasticOrthotropicSpec', 'J2plasticitySpec', 'Damage2pSpec', 'PressureindependmultiyieldSpec', 'PressuredependmultiyieldSpec', 'Pressuredependmultiyield02Spec', 'ContactSpec', 'ElasticSectionSpec', 'FiberSpec', 'FiberCustomSpec', 'FiberintSpec', 'PlateFiberSpec', 'ElasticMembranePlateSpec', 'LayeredshellSpec', 'GroundMotionRecordSpec', 'ElasticBeamColumnSpec', 'ElasticTimoshenkoBeamColumnSpec', 'ForceBasedBeamColumnSpec', 'DisplacementBasedBeamColumnSpec', 'FlexureShearInteractionDisplacementBasedBeamColumnSpec', 'TrussSpec', 'CorotationalTrussSpec', 'QuadSpec', 'ShellSpec', 'ShelldkgqSpec', 'Tri31Spec', 'QuadupSpec', 'StandardBrickElementSpec', 'AutoZeroLengthSpec', 'AutoEqualConstraintSpec']
